import type { Metadata } from "next";

import "../styles/reset.css";
import "../styles/globals.css";
import Header from "@/components/Header";

export const metadata: Metadata = {
    title: "올페이즈 과제: 이재호",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ko">
            <body>
                <Header />
                {children}
            </body>
        </html>
    );
}
